server:
  port: 8081
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 30
        max-idle: 15
        max-wait: 2000
        min-idle: 10
      shutdown-timeout: 10000